# Generated by Django 2.2.28 on 2023-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256)),
                ('modem', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'Not supported'), (1, 'Maybe supported'), (2, 'Supported')])),
                ('drvmini', models.CharField(blank=True, max_length=256)),
                ('vid1', models.CharField(blank=True, max_length=32)),
                ('pid1', models.CharField(blank=True, max_length=32)),
                ('vid2', models.CharField(blank=True, max_length=32)),
                ('pid2', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('provider', models.CharField(blank=True, max_length=256)),
                ('vpivci', models.CharField(blank=True, max_length=256)),
                ('synchbin', models.CharField(blank=True, max_length=256)),
                ('chipset', models.CharField(blank=True, max_length=256)),
                ('synch_alt', models.CharField(blank=True, max_length=16)),
                ('pppoeci_alt', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
