# SPDX-FileCopyrightText: 1999-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    ".gitignore",
    ".mailmap",
    "AUTHORS.md",
    "README.md",
    "flashtux/coding/_i18n_*.py",
    "flashtux/coding/migrations/*.py",
    "flashtux/eciadsl/_i18n_*.py",
    "flashtux/eciadsl/migrations/*.py",
    "flashtux/home/_i18n_*.py",
    "flashtux/home/migrations/*.py",
    "flashtux/image/migrations/*.py",
    "flashtux/news/_i18n_*.py",
    "flashtux/news/migrations/*.py",
    "flashtux/templates/**",
    "flashtux/w3blacklist/_i18n_*.py",
    "flashtux/w3blacklist/migrations/*.py",
    "media/.htaccess",
    "media/images/**",
    "requirements.txt",
]
SPDX-FileCopyrightText = "1999-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "media/css/bootstrap*.css",
    "media/js/bootstrap*.js",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "media/js/jquery*.js",
]
SPDX-FileCopyrightText = "OpenJS Foundation and other contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "media/pgp/*",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
