# Generated by Django 2.2.28 on 2023-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'home'), ('weechat', 'weechat'), ('eciadsl', 'eciadsl'), ('weewm', 'weewm'), ('w3blacklist', 'w3blacklist'), ('gmemo', 'gmemo'), ('flashtris', 'flashtris'), ('coding', 'coding'), ('games', 'games')], max_length=32)),
                ('category', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'category', 'priority'],
            },
        ),
    ]
