# Generated by Django 2.2.28 on 2023-04-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'home'), ('weechat', 'weechat'), ('eciadsl', 'eciadsl'), ('weewm', 'weewm'), ('w3blacklist', 'w3blacklist'), ('gmemo', 'gmemo'), ('flashtris', 'flashtris'), ('coding', 'coding'), ('games', 'games')], max_length=32)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('comment_relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Comment')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Info')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
