# -*- coding: utf-8 -*-
# This file is auto-generated after changes in database, DO NOT EDIT!

"""Translations for w3blacklist/letter."""

# flake8: noqa

from django.utils.translation import gettext_noop


def __i18n_w3blacklist_letter():
    """Translations for w3blacklist/letter."""
    # Translators: Letter: Gecko-based browsers
    gettext_noop("Madam, Sir,\n\nI have tested your website ([[URL]]) with various standard-compliant browsers, including Mozilla/Firefox and [[ANY OTHER W3C COMPLIANT BROWSER AFFECTED]]. And in the current state of things, your website does not work well (or at all) with those browsers.\n\nProblem is the following: [[PROBLEM DESCRIPTION]].\n\n[[HOW TO FIX IT (OPTIONAL)]]\n\nBy fixing this problem you allow your visitors to enjoy the content and services you offer.\n\nYou probably know that Microsoft will not release any other version of Internet Explorer for Windows as a standalone application, but as part of each new release of Windows, which mean IE's next version is due on 2006 along with Windows \"Vista\". Until then, IE won't benefit from any technical improvement and is naturally going to loose marketshare to actively developed and more standard-compliant browsers such as Mozilla, Opera and Safari.\n\nBy supporting Mozilla Gecko (the most W3C standard-compliant rendering engine to date), you also allow other browsers respectful of standards (Firefox, Camino, Epiphany, Galeon, Konqueror, Opera, Safari, etc.) to use your website, and therefore widen your audience. A XitiMonitor inquire shows that today almost 15% of net surfers are using Mozilla/Firefox everywhere in Europe (http://www.xitimonitor.com/etudes/equipement7.asp).\n\nI would like to hear from you regarding when you plan modifying your website to make it compatible.\n\nBest regards.\n\n[[SIGNATURE]]")
    # Translators: Letter: W3C compliant browsers (by Laurent Pelecq)
    gettext_noop("Madam, Sir,\n\nI have tested your website ([[URL]]) with various standard-compliant browsers, including Mozilla/Firefox and [[ANY OTHER W3C COMPLIANT BROWSER AFFECTED]]. And in the current state of things, your website does not work well (or at all) with those browsers.\n\nProblem is the following: [[PROBLEM DESCRIPTION]].\n\n[[HOW TO FIX IT (YOU CAN ADD THE BUGZILLA REFERENCE IF AVAILABLE [1])]]\n\nYou probably know Mozilla [2] is based on the Gecko rendering engine, which is used by numerous browsers, such as Galeon, and that Safari [3], the new browser from Apple, is based on the rendering engine of Konqueror [4]. You probably have also read in the press that Microsoft should no longer release upgrades to Internet Explorer. The ones who don't want, or can't, upgrade their Microsoft Windows system will more and more look for alternatives.\n\nBy supporting standard-compliant browsers, you allow anyone to access your website. Notably, you allow access to sight-impaired [5]. You'll find links and resources on inter-operability workgroup pages [6], AFUL [7] and OpenWeb website [8].\n\nI would be please to assist you and provide any additional information you may need.\n\nBest regards.\n\n[[SIGNATURE]]\n\n[1] Bugzilla #??????\nhttp://bugzilla.mozilla.org/show_bug.cgi?id=...\n\n[2] Mozilla\nhttp://www.mozilla.org/\n\n[3] Safari, Mac OS X web browser\nhttp://www.apple.com/safari/\n\n[4] Konqueror\nhttp://www.konqueror.org/\n\n[5] Web accessibility for handicapped people\nhttp://www.ddm.gouv.fr/dossiers_thematiques/documents/cisi2003g2.html\n\n[6] Groupe de travail sur l'interopérabilité de l'AFUL\nhttp://www.aful.org/gdt/interop/\n\n[7] L'Association Francophone des Utilisateurs de Linux et des Logiciels Libres\nhttp://www.aful.org/\n\n[8] Le groupe OpenWeb, première ressource francophone sur les standards web\nhttp://openweb.eu.org/")
    # Translators: Letter: IE only websites
    gettext_noop("Madam, Sir,\n\nI tried to access your site ([[URL]]) with various standard-compliant browsers, including Mozilla/Firefox and [[ANY OTHER W3C COMPLIANT WEB BROWSER AFFECTED]], but I always get booted and redirected to a page stating my configuration doesn't fit the minimun requirements ([[URL OF THE PAGE YOU'RE REDIRECTED TO]]).\n\nDespite what you may think, not everyone has or can use Internet Explorer. It simply does not exist on some platforms and due to major security issues (see http://www.guninski.com/browsers.html and http://die.leox.com/ie_unpatched/index.html), it's not a browser of choice for many people.\n\nThat automatic redirection was as surprising as your site does not actually need those minimun requirments. Thanks to some hacks and tricks, I've been able to bypass the detection scripts and finally access any part of your site flawlessly.\n\nThis proves Internet Explorer is not compulsory to browse your website.\n\nYou should remove your detection scripts and let people access the content of your site. This will help you to widen your audience and I think it's what you're looking for by setting up a website.\n\nBest regards.\n\n[[SIGNATURE]]")
    # Translators: Letter: Banks
    gettext_noop("Madam, Sir,\n\nI contact you because I can't use your service [[SERVICE NAME]] with my current web browser ([[YOUR BROWSER]]). I noticed you recommend to use Internet Explorer but I don't want to, because\n[[(CHOOSE BETWEEN)]] I'm running the Linux operating system and Internet Explorer doesn't work on this platform.\n[[(OR)]] you're maybe aware the numerous security holes of this browser (see http://www.guninski.com/browsers.html and http://die.leox.com/ie_unpatched/index.html ) are not suited for the financial operations I plan to do on your site.\n\nI would like to know when you will support customers using modern and W3C standard-compliant browsers, such as Netscape 7, Mozilla, Galeon and many others. If it's not envisaged in a near future, or if you don't respond, please note that I will move to a bank that will best fit the need of its customers.\n\nBest regards.\n\n[[SIGNATURE]]")
