# Generated by Django 2.2.28 on 2023-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('operating_system', models.CharField(max_length=256)),
                ('prog_language', models.CharField(max_length=64)),
                ('shortdesc', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('images', models.CharField(blank=True, max_length=1024)),
                ('filename', models.CharField(max_length=256)),
                ('filename_description', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
